### PR TITLE
Testbranch a3

### PR DESCRIPTION
**Pull request by nerdalertdk**

### CODE REVIEW

**Comment by nerdalertdk** [comment]
spawn_soldier.sqf - works
spawn_static.sqf - works
minefield.sqf - works

remote/remote.sqf - works, but only testede radio :)
vehicle_patrol.sqf - Semi works, soldier Ai sometime tries to kill veh.
heli_patrol.sqf - Think i have same problem as above.

find_position_new.sqf - new position system, works really great from my tests

only debug.sqf and sniper_team.sqf is migrated to A3

**Comment by nerdalertdk** [comment]
Think is the bandit_behaver that make ai fight

**Comment by nerdalertdk** [comment]
The vech patrol starts 1000m out, but sometime they get tag as Aggressors

```
2015/02/06,  8:50:37 "WAI: Spawning vehicle patrol at "112887""
2015/02/06,  8:50:37 "WAI: Driving to "112887""
2015/02/06,  8:50:38 "WAI: Spawning vehicle driver O Alpha 2-3:1"
2015/02/06,  8:50:38 "WAI: Spawning vehicle gunner 1 O Alpha 2-3:2"
2015/02/06,  8:50:38 "WAI: Vehicle WP1 / [O Alpha 2-3,1]"
2015/02/06,  8:50:38 "WAI: Vehicle WP2 / [O Alpha 2-3,2]"
2015/02/06,  8:50:38 "WAI: Vehicle WP3 / [O Alpha 2-3,3]"
2015/02/06,  8:50:38 "WAI: Vehicle WP4 / [O Alpha 2-3,4]"
2015/02/06,  8:50:38 "WAI: Vehicle WP5 / [O Alpha 2-3,5]"
2015/02/06,  8:50:38 "WAI: Vehicle WP6 / [O Alpha 2-3,6]"
2015/02/06,  8:50:38 "WAI: Vehicle WP7 / [O Alpha 2-3,7]"
2015/02/06,  8:50:38 "WAI: Vehicle WP8 / [O Alpha 2-3,8]"
2015/02/06,  8:50:38 "WAI: Vehicle WP9 / [O Alpha 2-3,9]"
2015/02/06,  8:50:38 "WAI: Vehicle WP10 / [O Alpha 2-3,10]"
2015/02/06,  8:50:38 "WAI: Spawning vehicle patrol at "110896""
2015/02/06,  8:50:38 "WAI: Driving to "112887""
2015/02/06,  8:50:38 "WAI: Spawning vehicle driver O Alpha 3-1:1"
2015/02/06,  8:50:38 "WAI: Spawning vehicle gunner 1 O Alpha 3-1:2"
2015/02/06,  8:50:38 "WAI: Vehicle WP1 / [O Alpha 3-1,1]"
2015/02/06,  8:50:38 "WAI: Vehicle WP2 / [O Alpha 3-1,2]"
2015/02/06,  8:50:38 "WAI: Vehicle WP3 / [O Alpha 3-1,3]"
2015/02/06,  8:50:38 "WAI: Vehicle WP4 / [O Alpha 3-1,4]"
2015/02/06,  8:50:38 "WAI: Vehicle WP5 / [O Alpha 3-1,5]"
2015/02/06,  8:50:38 "WAI: Vehicle WP6 / [O Alpha 3-1,6]"
2015/02/06,  8:50:38 "WAI: Vehicle WP7 / [O Alpha 3-1,7]"
2015/02/06,  8:50:38 "WAI: Vehicle WP8 / [O Alpha 3-1,8]"
2015/02/06,  8:50:38 "WAI: Vehicle WP9 / [O Alpha 3-1,9]"
2015/02/06,  8:50:38 "WAI: Vehicle WP10 / [O Alpha 3-1,10]"
2015/02/06,  8:50:44 "<infiSTAR.de>SL| DodgyMarker: MainBandit0 - [Bandits] MV22 Crash (v0097)"
2015/02/06,  8:50:44 "<infiSTAR.de>SL| DodgyMarker: MainBandit0dot - [Bandits] MV22 Crash (v0097)"
2015/02/06,  8:50:54 WARNING: Function 'name' - [WAI]465 is dead
2015/02/06,  8:50:54 "WAI: Unit:[WAI]465 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]136 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]38 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]446 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]383 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]830 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]851 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]839 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]667 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]332 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]715 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 "WAI: Shared Unit:[WAI]636 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:54 WARNING: Function 'name' - [WAI]707 is dead
2015/02/06,  8:50:54 "WAI: Unit:[WAI]707 Setting Aggressors:["Error: No vehicle"]"
2015/02/06,  8:50:56 Ragdoll - loading of ragdoll source "Soldier" started.
2015/02/06,  8:50:56 Ragdoll - loading of ragdoll source "Soldier" finished successfully.
2015/02/06,  8:50:56 "WAI: DELETE <NULL-object>"
2015/02/06,  8:50:56 "WAI: DELETE <NULL-object>"
2015/02/06,  8:50:56 "WAI: DELETE 4d48eb00# 1795250: offroad_01_hmg_f.p3d"


```

**Comment by nerdalertdk** [comment]
Vech. classname have nothing to do with it.
tried B_G_Offroad_01_armed_F and O_G_Offroad_01_armed_F

**Comment by nerdalertdk** [comment]
Could realy use some eyes on the AI vs AI thing :(

**Comment by nerdalertdk** [comment]
Last push is untested, lots of small changes but at core functions

**Comment by nerdalertdk** [comment]
So... The ai vs ai problem I've been having mass the mines :(

In arma 3 there is an createMine func.

Right now it means no ai vehicles when mine is true

**Comment by nerdalertdk** [comment]
@f3cuk are you online ?

**Comment by f3cuk** [comment]
Hey man,

Will be looking at all your changes in the weekend and merge them accordingly. I might have to setup a dev server first so i can help you test them. You could add me on skype (f3cuk-) to keep in contact :+1: 

Cheers,

f3cuk

**Comment by nerdalertdk** [comment]
I'm almost done ned to fix the patrol.sqf
But there's properly a bug or two :)

**Comment by f3cuk** [comment]
I did some bugfixes on them for the A2 branch (untested).

https://github.com/f3cuk/WICKED-AI/blob/Testbranch/WAI/compile/patrol.sqf
https://github.com/f3cuk/WICKED-AI/blob/Testbranch/WAI/compile/vehicle_patrol.sqf

**Comment by nerdalertdk** [comment]
Vehicle_patrol is working almost still Ned to find a better safe location

And the Ai is soooooooo bad at driving, fixed it a little by making the vehicle in God mode when players is not around,

**Comment by f3cuk** [comment]
Try to add a "safe" behaviour to the waypoints. Should be less prone to error.

**Comment by nerdalertdk** [comment]
Yeah but might be a problem if the mission position is in wildness/Forrest right now it set at the middle option

**Comment by nerdalertdk** [comment]
Got 3 missions running in prod :) no player have complained yet :)

**Comment by nerdalertdk** [comment]
Got the nuke to work and it's awesome !!!! Still some small twicks left
Still need to look at patrol.sqf and add more missions

You are welcome to test the mission on coolstone.dk

**Comment by nerdalertdk** [comment]
Any word on the adtions? 
Could use some more eyeson the code there is probably lots of places where the code could be optimized

**Pull request closed without merging**
